# .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WebAssembly
        working-directory: ./rust_wasm
        run: wasm-pack build --target web

      - name: Create Directories
        run: |
          mkdir -p public/assets
          mkdir -p src/lib/wasm

      - name: Copy WebAssembly Files
        run: |
          cp rust_wasm/pkg/dithering_wasm_bg.wasm public/assets/dithering_wasm.wasm
          cp rust_wasm/pkg/dithering_wasm.js src/lib/wasm/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: dist
          branch: gh-pages